### ISSUE TITLE
Align permalink rendering with site-kit

### ISSUE THREAD

**Issue by geoffrich** [sveltejs/action-deploy-docs#1]
https://github.com/sveltejs/sites/pull/32 was recently merged and changed how permalinks were rendered to improve a11y.

```html
<!-- before: no link text, invalid aria attribute -->
<a href="docs#introduction" class="anchor" aria-hidden></a>
<!-- after: hidden link text for screen readers -->
<a href="docs#introduction" class="anchor"><span class="visually-hidden">permalink</span></a>
```

Since most of the docs markdown is being rendered via this repo, changes need to be made here as well so that permalinks are rendered consistently. This will also resolve several axe a11y errors on the SvelteKit docs.

I'm happy to work on a PR for this, but wanted to start discussion in an issue first in case contributions aren't being accepted yet.

**Comment by Rich-Harris** [comment]
I'm working on some changes to how the docs components work (https://github.com/sveltejs/sites/pull/66), and stumbled upon here as a result. 

I'm actually starting to think that permalinks shouldn't be included in the HTML at all. Instead, they could be added in the browser. The reason for this is that we might want to take docs from other sources than the API (in my current case, mdsvex files), and in those cases we don't really want to recreate the logic for manipulating the markdown files everywhere when it's so easy to just add these things to the DOM.

Relatedly, I'd like to get rid of the `offset-anchor` elements. They're there to solve the fact that when you click on a link to `#foo`, a `<h2 id="foo">` component will snap to the top of the page (which is underneath the nav bar, but would be ugly even if it wasn't) but it turns out there's a [better solution](https://css-tricks.com/hash-tag-links-padding/) that results in more semantic HTML.

So far the only consumer of the docs API is kit.svelte.dev, so we should be able to update this without too much trouble, but stuff like this does make me wonder if it should be versioned.

**Comment by Rich-Harris** [comment]
this is now deployed (via https://github.com/sveltejs/action-deploy-docs/pull/5), so I'll close this. thanks!
